# Day1: Basic Python Quick Practice:

# Quick Practice
#### Create a welcome inteface
#### Ask user to enter their age
#### if age is greater than 18 then ask them to create a user name and password ask to enter
#### if user name is correct then request for password
#### if password is correct mention Welcome and create your profile

In [2]:
print("Welcome")
print("Enter your age:")
age=int(input())
if age>18:
    print("Create username and password")
    username=input("Username: ")
    password=input("Password: ")
    print("Enter username and password: ")
    username_entered=input("Username: ")
    if username_entered==username:
        password_entered=input("Password: ")
        if password_entered== password:
            print("Welcome and create your profile")
        else:
            print("Incorrect password")
    else:
        print("Incorrect username")
else:
    print("Access denied, age<18")

Welcome
Enter your age:


 20


Create username and password


Username:  yyy
Password:  123


Enter username and password: 


Username:  yyy
Password:  123


Welcome and create your profile


# Day2: Numpy Quick Practice:
#### Create an array using arange function starting with 50 and end with 10.
#### reshape it to 2D array

In [3]:
import numpy as np

In [4]:
arr=np.arange(50,9,-1)
print(arr)

[50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27
 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [10]:
arr_2D= arr.reshape(1,41)
print(arr_2D)

[[50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27
  26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]]


# Quick Practice:
#### Create a 4x4 matrix of all fives.
#### Create an array of 20 numbers between 10 and 50 (inclusive).

In [5]:
matrix=np.full((4,4),5)
print(matrix)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [7]:
array=np.linspace(10,50,20, dtype="int")
print(array)

[10 12 14 16 18 20 22 24 26 28 31 33 35 37 39 41 43 45 47 50]


# Quick Practice:
#### Extract every 2nd element from an array of numbers 0-20.
#### From a 3x3 matrix, extract the last column

In [14]:
array1= np.arange(0,21)
print(array1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [15]:
array1_sec_element= array1[::2]
print(array1_sec_element)

[ 0  2  4  6  8 10 12 14 16 18 20]


In [16]:
matrix1= np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print(matrix1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [17]:
matrix1_last_col= matrix1[:,2]
print(matrix1_last_col)

[3 6 9]


# Day3: Pandas Lets Practice
#### Check null values for the given data
#### replace null values by mean/median/mode
#### describe

In [36]:
import pandas as pd
details = {'Brand':pd.Series(['Nokia','Asus',"Nokia","Nokia",'Samsung',"ABC",'Micromax','Apple','MI','Zen',"Apple"]),
   'Price':pd.Series([10000,8000,12500,7000,40000,12000,12999,13999,59999]),
   'Rating(10)':pd.Series([7,6.5,8.5,9,8,9.5,7,9])
}

d = pd.DataFrame(details)
d

Brand    Price  Rating(10)
0      Nokia  10000.0         7.0
1       Asus   8000.0         6.5
2      Nokia  12500.0         8.5
3      Nokia   7000.0         9.0
4    Samsung  40000.0         8.0
5        ABC  12000.0         9.5
6   Micromax  12999.0         7.0
7      Apple  13999.0         9.0
8         MI  59999.0         NaN
9        Zen      NaN         NaN
10     Apple      NaN         NaN

In [21]:
d.isnull().sum()

Brand         0
Price         2
Rating(10)    3
dtype: int64

In [34]:
d.describe()

count       11.000000
mean     18317.909091
std      16430.375148
min       7000.000000
25%      11000.000000
50%      12500.000000
75%      13499.000000
max      59999.000000
Name: Price, dtype: float64

In [39]:
for col in d.select_dtypes(include=[np.number]).columns:
    median_value=d[col].median()
    d[col].fillna(median_value)
print(d)

       Brand    Price  Rating(10)
0      Nokia  10000.0        7.00
1       Asus   8000.0        6.50
2      Nokia  12500.0        8.50
3      Nokia   7000.0        9.00
4    Samsung  40000.0        8.00
5        ABC  12000.0        9.50
6   Micromax  12999.0        7.00
7      Apple  13999.0        9.00
8         MI  59999.0        8.25
9        Zen  12500.0        8.25
10     Apple  12500.0        8.25
